[package]
name = "wgpu-renderer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
cgmath = "0.18.0"
env_logger = "0.10.0"
image = { version = "0.24.5", features = ["png", "jpeg"] }
log = "0.4.17"
pollster = "0.2.5"
wgpu = '0.14.0'
winit = "0.27.5"
